import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./Context/CartContext";
import { ReduxProvider } from "@/providers/ReduxProviders";
import { AuthProvider } from "@/providers/AuthProvider";
import LayoutClient from "./LayoutClient";
import { Toaster } from "react-hot-toast";
import ChatWidget from "./componets/chat/ChatWidget";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "FABRICE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${inter.variable} ${poppins.variable} antialiased`}>
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: { fontWeight: 600, fontSize: '14px', borderRadius: '12px' },
            success: { iconTheme: { primary: '#f97316', secondary: '#fff' } },
          }}
        />
        <CartProvider>
          <ReduxProvider>
            <AuthProvider>
              <LayoutClient>
                {children}
              </LayoutClient>
              <ChatWidget />
            </AuthProvider>
          </ReduxProvider>
        </CartProvider>
      </body>
    </html>
  );
}
